export enum position {
  "Assign" = "Assign",
  "AutoDefault" = "AutoDefault",
  "Bottom" = "Bottom",
  "BottomCenter" = "BottomCenter",
  "BottomLeft" = "BottomLeft",
  "BottomRight" = "BottomRight",
  "Center" = "Center",
  "Continuous" = "Continuous",
  "ContinuousBottom" = "ContinuousBottom",
  "ContinuousLeft" = "ContinuousLeft",
  "ContinuousRight" = "ContinuousRight",
  "ContinuousTop" = "ContinuousTop",
  "Left" = "Left",
  "LeftMiddle" = "LeftMiddle",
  "Perimeter" = "Perimeter",
  "Right" = "Right",
  "RightMiddle" = "RightMiddle",
  "Top" = "Top",
  "TopCenter" = "TopCenter",
  "TopLeft" = "TopLeft",
  "TopRight" = "TopRight"
}
